<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))" />

  <PropertyGroup>
    <IsTestProject>$(MSBuildProjectName.EndsWith("Tests"))</IsTestProject>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(IsTestProject)' == 'True' ">
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup Condition=" '$(IsTestProject)' == 'True' ">
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup Condition=" '$(IsTestProject)' == 'True' ">
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
