<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net472;net8.0;net9.0;net10.0</TargetFrameworks>
    <Description>Generates and injects SemVer or CalVer versions based on Git commits during the build of .NET projects.</Description>
    <VersionPrefix>0.1.0</VersionPrefix>
    <PackageId>Sorrend.MsBuild</PackageId>
    <PackageTags>SemVer; Semantic Versioning; CalVer; Calendar Versioning; Version; Versioning; AssemblyInfo; Commit; Git</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <NuspecFile>PackageFiles\Sorrend.MsBuild.nuspec</NuspecFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sorrend.Core\Sorrend.Core.csproj" />
  </ItemGroup>

  <Target Name="SetDefaultNuspecProperties" BeforeTargets="GenerateNuspec">
    <PropertyGroup>
      <NuspecProperties>
        id=$(PackageId);
        version=$(PackageVersion);
        author=$(Authors);
        title=$(Title);
        description=$(PackageDescription.Replace("&lt;", "&amp;lt;"));
        copyright=$(Copyright.Replace("&lt;", "&amp;lt;"));
        tags=$(PackageTags.Replace(";", "&#59;"));
        configuration=$(Configuration);
        $(NuspecProperties)
      </NuspecProperties>
    </PropertyGroup>
  </Target>

  <!-- see https://github.com/nuget/home/issues/14681 -->
  <PropertyGroup>
    <PackageReferenceCompatibleProjectStyle>true</PackageReferenceCompatibleProjectStyle>
  </PropertyGroup>

</Project>
