<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xunit.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sorrend.MsBuildTool\Sorrend.MsBuildTool.csproj">
      <CopyPackageToOutputDirectory>true</CopyPackageToOutputDirectory>
    </ProjectReference>
    <ProjectReference Include="..\Sorrend.IntegrationTests.Tools\Sorrend.IntegrationTests.Tools.csproj" />
  </ItemGroup>

  <Target Name="CopyProjectReferencePackagesToOutputDirectory" AfterTargets="CopyFilesToOutputDirectory">

    <MSBuild Projects="@(ProjectReference)"
             Targets="_GetOutputItemsFromPack"
             Properties="PackageReferenceCompatibleProjectStyle=true"
             Condition=" '%(ProjectReference.CopyPackageToOutputDirectory)' == 'true' ">
      <Output TaskParameter="TargetOutputs" ItemName="ProjectReferencePackOutput" />
    </MSBuild>

    <ItemGroup>
      <ProjectReferencePackage Include="@(ProjectReferencePackOutput)" Condition=" '%(Extension)' == '.nupkg' ">
        <TargetPath>$(OutDir)$([System.IO.Path]::GetFileNameWithoutExtension(%(OriginalItemSpec))).nupkg</TargetPath>
      </ProjectReferencePackage>
    </ItemGroup>

    <Copy SourceFiles="@(ProjectReferencePackage)"
          DestinationFiles="@(ProjectReferencePackage->'%(TargetPath)')"
          SkipUnchangedFiles="true">
      <Output TaskParameter="DestinationFiles" ItemName="FileWrites" />
    </Copy>

  </Target>

</Project>
